apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackaton-soat-manager
  namespace: hackaton-soat-manager
spec:
  selector:
    matchLabels:
      app: hackaton-soat-manager
  template:
    metadata:
      labels:
        app: hackaton-soat-manager
    spec:
      serviceAccountName: hackaton-soat-manager-sa
      containers:
        - name: hackaton-soat-manager
          image: srteixeiradias/hackaton-soat-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
          livenessProbe:
            httpGet:
              path: /api/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 3