apiVersion: v1
kind: Service
metadata:
  name: hackaton-soat-manager-service
  namespace: hackaton-soat-manager
  labels:
    app: hackaton-soat-manager
spec:
  type: ClusterIP
  selector:
    app: hackaton-soat-manager
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http