name: App Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:

  build:
    uses: ./.github/workflows/docker.yaml
    with:
      image_name: srteixeiradias/hackaton-soat-api
      image_tag: latest
    secrets:
      DOCKERHUB_LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    needs: build
    uses: ./.github/workflows/terraform.yaml
    with:
      environment: ${{ inputs.environment }}
      image_tag: latest
    secrets: inherit