name: Infra Deploy

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yaml
    with:
      environment: prod
      image_tag: keep
    secrets: inherit